######################################################################
# Automatically generated by qmake (3.0) Tue Mar 31 18:23:54 2015
######################################################################

TARGET = tim
TEMPLATE = lib
CONFIG += plugin c++11 debug
INCLUDEPATH += .
DESTDIR = timtest/imageformats

# Input
HEADERS += tim_p.hpp
SOURCES += tim.cpp
OTHER_FILES += tim.json

target.path += $$[QT_INSTALL_PLUGINS]/imageformats
INSTALLS += target
