######################################################################
# Automatically generated by qmake (3.0) Tue Mar 31 19:08:52 2015
######################################################################

TEMPLATE = app
TARGET = tim2png
INCLUDEPATH += .
CONFIG += console c++11 debug

# Input
SOURCES += tim2png.cpp
